<?php
return[
    'experienceThresholds' => [
        2  => 100,
        3  => 200,
        4  => 300,
        5  => 400,
        6  => 500,
        7  => 600,
        8  => 700,
        9  => 800,
        10  => 900,
        11  => 1000,
        12  => 1100,
        13  => 1200,
        14  => 1300,
        15  => 1400,
        16  => 1500,
        17  => 1600,
        18  => 1700,
        19  => 1800,
        20  => 1900
],

'abilitiesRogue' => [
    2  => "Ruse",
    3  => "Archétype de roublard",
    4  => "Amélioration de caractéristiques",
    5  => "Esquive instinctive",
    6  => "Expertise supèrieur",
    7  => "Esquive totale",
    8  => "Brise cote",
    9  => "Capacité de l'archétype de roublard",
    10 => "Force de la nature",
    11 => "Savoir-faire",
    12 => "Déplacement furtif",
    13 => "Sang froid",
    14 => "Perception aveugle",
    15 => "Esprit fuyant",
    16 => "Exécution",
    17 => "Poison",
    18 => "Insaisissable",
    19 => "Vole a la tire",
    20 => "Coup de chance",
],

'abilitiesBarbarian' => [
    2  => "Attaque téméraire, Sens du danger",
    3  => "Voie primitive",
    4  => "Amélioration de caractéristiques",
    5  => "Attaque supplémentaire, Déplacement rapide",
    6  => "Capacité de voie",
    7  => "Instinct sauvage",
    8  => "Brise genoux (1 dé)",
    9  => "Capacité de voie",
    10 => "Capacité de voie",
    11 => "Rage implacable",
    12 => "Brise genoux (2 dés)",
    13 => "Capacité de voie",
    14 => "Rage persistante",
    15 => "Brise genoux (3 dés)",
    16 => "Capacité de voie",
    17 => "Brise genoux (4 dés)",
    18 => "Puissance indomptable",
    19 => "Tourbillon",
    20 => "Champion primitif",
],
];